FIX #32178: repair.php: fix missing 'as' with Postgres (#32179)
Fix the following SQL error when executing the repair script on 19.0.x
and above.

        Error DB_ERROR_SYNTAX (Req 159): create table tmp_bank_url_expense_user (select e.fk_user_author, bu2.fk_bank from llx_expensereport as e, llx_bank_url as bu2 where bu2.url_id = e.rowid and bu2.type = 'payment_expensereport');
        ERROR: 42601: syntax error at or near "select" LINE 1: create table tmp_bank_url_expense_user (select e.fk_user_aut... ^ LOCATION: scanner_yyerror, scan.l:1145